# Generated by Django 4.2.1 on 2023-06-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='description',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
        migrations.AddField(
            model_name='stock',
            name='close_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stock',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='stock',
            name='high_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stock',
            name='low_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stock',
            name='open_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stock',
            name='volume',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(max_length=50),
        ),
    ]
